// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(WebApiDBContext))]
    [Migration("20191109122927_ogrenciList")]
    partial class ogrenciList
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.Ogrenci", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Isim")
                        .IsRequired();

                    b.Property<string>("KimlikNo")
                        .IsRequired();

                    b.Property<string>("Ogretmenler");

                    b.Property<string>("Okullar");

                    b.Property<string>("SoyIsım")
                        .IsRequired();

                    b.HasKey("_id");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("Domain.Entities.Ogretmen", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Isim")
                        .IsRequired();

                    b.Property<string>("KimlikNo")
                        .IsRequired();

                    b.Property<string>("Okullar");

                    b.Property<string>("SoyIsım")
                        .IsRequired();

                    b.HasKey("_id");

                    b.ToTable("Ogretmenler");
                });

            modelBuilder.Entity("Domain.Entities.Okul", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .IsRequired();

                    b.Property<string>("Adres")
                        .IsRequired();

                    b.Property<string>("Ilce")
                        .IsRequired();

                    b.Property<string>("Ogrenciler");

                    b.Property<string>("Sehir")
                        .IsRequired();

                    b.HasKey("_id");

                    b.ToTable("Okullar");
                });
#pragma warning restore 612, 618
        }
    }
}
